### ISSUE TITLE
A possible enhancement......

### ISSUE THREAD

**Issue by geogerar** [kirualex/KAProgressLabel#14]
Hello,
Thanks for your excellent tool.
I would like to propose a possible enchancement...
Can you make to set up your tool programmatically and not only in IB?
Because when I tried to do it I got a crash and some warnings because of weak set up.
Thanks  again.

George Gerardis

**Comment by kirualex** [comment]
It also works quite well programmatically, just make sure you declare your `KAProgressLabel` as a strong property : 
```objective-c
@property (strong,nonatomic)  KAProgressLabel * pLabel;
```

Then just do as you would with any UILabel : 

```objective-c
self.pLabel = [[KAProgressLabel alloc] initWithFrame:CGRectMake(20, 40, 100, 100)];
[self.view addSubview:self.pLabel];
```

**Comment by geogerar** [comment]
Thanks for your response.....
I Know, I have done all these and I get a warning.....in the following method..
        self.pLabel1.startLabel.text = [NSString stringWithFormat:@"%.f",self.pLabel1.progress*100];
    };
The warning is ....
Capturing 'self' strongly in this block is likely to lead to a retain cycle

and also when I go back in my previous controller my app crashes........

Any ideas?

Thanks again

George

**Comment by kirualex** [comment]
Just use weakSelf when using `self` in a block : 

```objective-c
__unsafe_unretained Demo1 * weakSelf = self;
    self.pLabel.labelVCBlock = ^(KAProgressLabel *label) {
        weakSelf.pLabel.startLabel.text = [NSString stringWithFormat:@"%.f",weakSelf.pLabel.startDegree];
    };
```

You can also use this awesome library to handle retain cycles : https://github.com/jspahrsummers/libextobjc

**Comment by geogerar** [comment]
what is Demo1 in following sentence?

__unsafe_unretained Demo1 * weakSelf = self;


On Wed, Mar 18, 2015 at 5:15 PM, Alexis Creuzot <notifications@github.com>
wrote:

> Just use weakSelf when using self in a block :
>
> __unsafe_unretained Demo1 * weakSelf = self;
>     self.pLabel.labelVCBlock = ^(KAProgressLabel *label) {
>         weakSelf.pLabel.startLabel.text = [NSString stringWithFormat:@"%.f",weakSelf.pLabel.startDegree];
>     };
>
> You can also use this awesome library to handle retain cycles :
> https://github.com/jspahrsummers/libextobjc
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kirualex/KAProgressLabel/issues/14#issuecomment-83018328>
> .
>



-- 
*Γιώργος Ν. Γεράρδης*

**Comment by kirualex** [comment]
Well this is whatever object holding a reference to the property you need in your block. Usually your `UIViewController`.
This is pretty basic stuff, you should maybe try this link for more infos on retain cycles : http://www.cocoawithlove.com/2009/07/rules-to-avoid-retain-cycles.html

I'm closing this issue as it is not about the component anymore. You'll find help on StackOverflow if you need to go deeper in this.

**Comment by geogerar** [comment]
OK....
Thank you very very much for your help!

George


On Wed, Mar 18, 2015 at 5:32 PM, Alexis Creuzot <notifications@github.com>
wrote:

> Well this is whatever object holding a reference to the property you need
> in your block. Usually your UIViewController.
> This is pretty basic stuff, you should maybe try this link for more infos
> on retain cycles :
> http://www.cocoawithlove.com/2009/07/rules-to-avoid-retain-cycles.html
>
> I'm closing this issue as it is not about the component anymore. You'll
> find help on StackOverflow if you need to go deeper in this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kirualex/KAProgressLabel/issues/14#issuecomment-83022273>
> .
>



-- 
*Γιώργος Ν. Γεράρδης*
