### ISSUE TITLE
Gradient in Progress Color

### ISSUE THREAD

**Issue by yj7** [kirualex/KAProgressLabel#21]
Would really like the ability to set a gradient as the progress bar's color

**Comment by kirualex** [comment]
This is definitely something interesting. I'm not sure how difficult this may be, I'll have a look.

**Comment by kirualex** [comment]
After some research it appears that Apple does not provide a way to achieve an angle gradient with the CoreGraphics framework. 
So the steps are : 
- Find an implementation of angle gradients using CoreGraphics
- Create a rect layer with an angle gradient for track and progress
- Clip each gradient layers based on track and progress paths

A nice touch would be to allow the user to choose between a dynamic and static gradient for the progress.

**Comment by SikanderZeb** [comment]
I got it working, in case you still need it. In KAProgressLabel class, in `-(void)drawProgressLabelCircleInRect:(CGRect)rect` method replace the following code after `//Progress` lines 

` // Progress
    
    CGContextSetStrokeColorWithColor(context, self.progressColor.CGColor);
    CGContextSetLineWidth(context, _progressWidth);
    CGContextAddArc(context, archXPos,archYPos, archRadius, progressStartAngle, progressEndAngle, 0);
    
    CAShapeLayer *arc = [CAShapeLayer layer];
    arc.path = CGContextCopyPath(context);
    
    CGContextStrokePath(context);
   
    arc.fillColor = [UIColor clearColor].CGColor;
    arc.strokeColor = [UIColor purpleColor].CGColor;
    arc.lineWidth = _progressWidth;

    CAGradientLayer *gradientLayer = [CAGradientLayer layer];
    gradientLayer.frame = rect;
    gradientLayer.colors = @[(__bridge id)[UIColor greenColor].CGColor,(__bridge id)[UIColor whiteColor].CGColor ];
    [self.layer addSublayer:gradientLayer];
    
    gradientLayer.mask = arc;`

And it would add a gradient with two colors.

Thanks,
Sikander

**Comment by kirualex** [comment]
I'll look into it, this could make a nice addition to the library

**Comment by kirualex** [comment]
After looking more closely into it, there are a few issues. What we need is not a simple linear or radial gradient, but an angle gradient, which is not available on `CAGradientLayer`. 
I'll look into third parties libs / code if anything could fit into this library to handle this feature.
