### ISSUE TITLE
Multiple progress view in same circle

### ISSUE THREAD

**Issue by paulantony87** [kirualex/KAProgressLabel#22]
Is it possible to have multiple sliders for multiple colors (say 3), 1 going clockwise and another anticlockwise/ the third starting where 1 finishes and ending where 2 stops.

http://users.infragistics.com/2013.1/Ignite/DoughnutChart.PNG

all the colors controlled by respective sliders based on a percentage of total value implied. Slider can also have value zero/100%

**Comment by kirualex** [comment]
This is mostly a chart behaviour you're describing, which isn't really what we're aiming in this library.
Maybe this might better suit your needs : https://github.com/yasuoza/XYDoughnutChart

**Comment by paulantony87** [comment]
Thank you. I did resolve with a similar library to the doughnut.
