### ISSUE TITLE
UIScrollView or TextView scroll event blocks UIView animation

### ISSUE THREAD

**Issue by f1rstattack** [kirualex/KAProgressLabel#25]
Hi I'm using progress label to show a countdown timer with animation.
My view has a scrollview and a textview with kaprogresslabel.
And if i scroll one of them.
  kaprogresslabel's setStartDegree: with TPPropertyAnimationTimingLinear animation breaks

i read http://stackoverflow.com/questions/16557846/uiscrollview-scroll-event-blocks-uiview-animation

and I change 

- (void)addAnimation:(TPPropertyAnimation *)animation {
    
    if ( !animations ) {
        animations = [[NSMutableArray alloc] init];
    }
    
    [animations addObject:animation];
    
    if ( !timer ) {
        if ( NSClassFromString(@"CADisplayLink") != NULL ) {
            timer = [CADisplayLink displayLinkWithTarget:self selector:@selector(update:)];
            // #revision
            //[timer addToRunLoop:[NSRunLoop currentRunLoop] forMode:NSDefaultRunLoopMode];
            [timer addToRunLoop:[NSRunLoop currentRunLoop] forMode:NSRunLoopCommonModes];
            // ##
        } else {
            timer = [NSTimer scheduledTimerWithTimeInterval:kRefreshRate target:self selector:@selector(update:) userInfo:nil repeats:YES];
        }
    }
}

in TPPropertyAnimation.m 

I changed NSRunLopp mode to NSRunLoopCommonModes

and it works fine for me now
  fyi

**Comment by kirualex** [comment]
I'm pushing a quick fix for now, but the best way to handle this would be to allow the developer to choose a custom run loop.
