### ISSUE TITLE
How to use labelVCBlock in swift??

### ISSUE THREAD

**Issue by andre991** [kirualex/KAProgressLabel#26]
lblProgress.labelVCBlock = ^(KAProgressLabel *label) {
    label.text = [NSString stringWithFormat:@"%.f", (label.progress/100)*total*100];
    };

**Comment by rock3m** [comment]
This is my code in Swift:

    self.uploadProgressLabel.labelVCBlock = { label in
        label.text = String(format: "%.0f%%", (label.progress * 100))
    }
