### ISSUE TITLE
Animation has not been stopped correctly

### ISSUE THREAD

**Issue by nguyenhuynhkhanh** [kirualex/KAProgressLabel#28]
Current implementation of the stop animation might cause SIGABRT when it's called twice.
The reason is when the cancel function itself remove the object. But the _currentAnimation might still point to them in a short period. This lead to an invalid reference and cause SIGABRT

```java
- (void) stopAnimations
{
    if (_currentAnimation != nil) {
        [_currentAnimation cancel];
         }
}
```

Proposal:
```java
- (void) stopAnimations
{
    if (_currentAnimation != nil) {
        [_currentAnimation cancel];
      _currentAnimation = nil;
         }
}
```

**Comment by alexoverseer** [comment]
Confirm that. It happens when i call it at progress=1, startDegree=0, endDegree=360.
