### ISSUE TITLE
Progress Label Text change automatically

### ISSUE THREAD

**Issue by yatendray** [kirualex/KAProgressLabel#37]
Hi

When I am using 

    `self.pLabel.progress = 0.75;`

then I can successfully change pLabel text 
But when I am using 

    `[self.pLabel setProgress:0.75 timing:TPPropertyAnimationTimingEaseInEaseOut duration:1 delay:0];`

then pLabel text in not updating and it's **showing percentage instead of text.**

It's bug ?

**Comment by kirualex** [comment]
did you implement the `labelValueChangedCompletion` block?

**Comment by yatendray** [comment]
I tried with these type of codes

Type:1
 [self.pLabel setProgress:0.75 timing:TPPropertyAnimationTimingEaseInEaseOut duration:1 delay:0];

Type :2
    self.pLabel.labelAnimCompleteBlock = ^(KAProgressLabel *label) {
     
      NSLog(@"Animation complete !");
       [self.pLabel setProgress:0.75 timing:TPPropertyAnimationTimingEaseInEaseOut duration:1 delay:0];

    };

but nothing work.if I am wrong, please let me know

**Comment by kirualex** [comment]
Do try like in the Demo : 
```
self.pLabel.labelVCBlock = ^(KAProgressLabel *label) {
        CGFloat delta = label.endDegree - label.startDegree;
        label.text = [NSString stringWithFormat:@"%.0f%%", (delta / 3.6f)];
 };
[self.pLabel setProgress:0.75 timing:TPPropertyAnimationTimingEaseInEaseOut duration:1 delay:0];
```
