### ISSUE TITLE
TPPropertyAnimation RunLoop change causes UI updates in non-main thread

### ISSUE THREAD

**Issue by AndyWeinstein** [kirualex/KAProgressLabel#38]
I took the latest version of the code and started getting UI update in other than main thread exceptions.
Looked at the diff to what I had been using and found the following line had changed:

        [timer addToRunLoop:[NSRunLoop currentRunLoop] forMode:NSRunLoopCommonModes]; // TODO/ custom loop mode 

when I returned the code to use NSDefaultRunLoopMode the problem went away.

**Comment by kirualex** [comment]
fixed with 3.3.2
